version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

